### PR TITLE
WIP: Add a readme. 

### PR DESCRIPTION
**Pull request by beala-stripe**
This adds a readme with some TODOs. I think it's best to leave this as a WIP PR until we get a license up.

I had to add scala-library as a compile time dep. The example-readme wasn't running without it, and I didn't want to spend more time debugging that. This is why all the tests changed (side note: updating the tests is brutal).

### CODE REVIEW

**Comment by andyscott** [comment]
👍

Nice work on the readme.

**Comment by joprice** [comment]
Very useful. I was able to generate a build for djinni https://github.com/joprice/djinni/tree/bazel/src. Worked the first try.

**Comment by beala-stripe** [comment]
@joprice Awesome! Glad to hear it's working for you!

I added a LICENSE file. I'm removing the WIP title. Will work on publishing the artifact next and we can update the readme when that happens.

**Comment by andyscott** [comment]
Not sure why the build failed. I've cleared the Travis caches and restarted it.

**Comment by beala-stripe** [comment]
TravisCI is being really flakey for some reason. The tests were failing nondeterministically with `Remote sbt initialization failed` (1 test the first run, 2 tests the second run). I googled a bit and there are other people asking about this, but no real solution that I could find.

It failed just now with `sbt-launch-lib.bash: line 59: 6770 Killed`.

**Comment by andyscott** [comment]
I'm okay merging this as is, despite the build failure given that it's a CI issue and not a project issue.

**Pull request merged**
